name:                real-world-haskell
version:             0.1.0.0
author:              "Gustavo Bicalho"

dependencies:
- base >= 4.7 && < 5
- bytestring
- regex-posix
- filepath
- directory
- array
- containers
- mtl
- parsec
- time

library:
  source-dirs: src
