name:                algebra-driven-design
version:             0.1.0.0
author:              "Gustavo Bicalho"

description: Exercises from the book "Algebra Driven Design"

dependencies:
- base >= 4.7 && < 5
- transformers
- containers
- multiset
- monoidal-containers
- generic-data

library:
  source-dirs: src
tests:
  test:
    main: Spec.hs
    source-dirs:
    - test
    - src
    dependencies:
    - hspec
    - QuickCheck
    - quickspec

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wno-name-shadowing
- -foptimal-applicative-do

default-extensions:
- DeriveGeneric
- DeriveDataTypeable
- EmptyDataDeriving
- DerivingStrategies
- PatternSynonyms
- TypeApplications
